### ISSUE TITLE
Request: How to trigger for a different branch

### ISSUE THREAD

**Issue by rowi1de** [CircleCI-Public/trigger-circleci-pipeline-action#12]
### Is there an existing issue that is already proposing this?

- [X] I have searched the existing issues https://discuss.circleci.com/t/github-actions-circleci-how-to-trigger-for-a-different-branch/43143

### Is your feature request related to a problem? Please describe it

```yaml
# Circle CI will build master and all PRs anyway, we just need to trigger non-default branches
name: Trigger CircleCI Build on Beta and Release Branch

on:
  push:
   branches:
   - beta
   - release


jobs:
  trigger-build:
    runs-on: ubuntu-latest

    steps:
      - name: Trigger CircleCI
        id: trigger-circle-ci
        uses: CircleCI-Public/trigger-circleci-pipeline-action@v1.0
        env:
          CCI_TOKEN: ${{ secrets.CIRCLE_TOKEN }}
```
should trigger CircleCI for the Branch the GitHub Action was triggered for

### Describe the solution you'd like

- The action should have an option "current-branch:true" ajd determine the branch from the GItHub Event
- Optional Parameter for the Action to set a branch manually 

### Teachability, documentation, adoption, migration strategy

...

### What is the motivation / use case for changing the behavior?

Make GitHub Action & Circle CI Integration smooth
