### ISSUE TITLE
Request: Add ability to trigger another org's circleci pipeline

### ISSUE THREAD

**Issue by h-parekh** [CircleCI-Public/trigger-circleci-pipeline-action#14]
### Is there an existing issue that is already proposing this?

- [X] I have searched the existing issues

### Describe the solution you'd like

It seems like the current implementation is parsing `repoOrg` and `repoName`  from the payload's repository URL and using those to invoke circleCI's [v2 endpoint](https://circleci.com/docs/api/v2/#operation/triggerPipeline)

```js
// https://github.com/CircleCI-Public/trigger-circleci-pipeline-action/blob/main/dist/index.js#L12707
const [, , repoOrg, repoName] = pattern.exec(payload.repository.url);
...
...
// https://github.com/CircleCI-Public/trigger-circleci-pipeline-action/blob/main/dist/index.js#L12755
const url = `https://circleci.com/api/v2/project/gh/${repoOrg}/${repoName}/pipeline`;
```

Allow a user to optionally specify `REPO_ORG` and `REPO_NAME` [as the job's env variables](https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#jobsjob_idstepsenv) which would take precedence over the default parsing. 

```yaml
on:
  pull_request:
    types: [opened, reopened, synchronize, assigned, edited]
jobs:
  trigger-circleci:
    runs-on: ubuntu-latest
    steps:
      - name: CircleCI Trigger on Pull Request
        id: <customize id>
        uses: CircleCI-Public/trigger-circleci-pipeline-action@v1.0
        env:
          REPO_ORG: "organization-name"
          REPO_NAME: "repo-name"
          CCI_TOKEN: ${{ secrets.CCI_TOKEN }}
```

### Teachability, documentation, adoption, migration strategy

REPO_ORG and REPO_NAME are optional env variables that you can pass in as env variable to the job 
https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#jobsjob_idstepsenv

### What is the motivation / use case for changing the behavior?

This action links two tools, which is more likely to be prevalent on teams that work across different github orgs.
