### ISSUE TITLE
Bug: Example in documentation causes yaml error

### ISSUE THREAD

**Issue by realnc** [CircleCI-Public/trigger-circleci-pipeline-action#17]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

This example shown in the documentation on how to avoid double execution does not work:

```yaml
workflows:
  # This workflow is set to be conditionally triggered,
  # only via the GitHub Action.
  # With no other unfiltered workflows, normal push events will be ignored.
  when: << pipeline.parameters.GHA_Action >>
  test:
    jobs:
      - test
```

It causes the CircleCI pipeline to fail with:

```text
#!/bin/sh -eo pipefail
# ERROR IN CONFIG FILE:
# [#/workflows/when] only 0 subschema matches out of 2
# 1. [#/workflows/when] expected type: Mapping, found: String
# |   SCHEMA:
# |     type: object
# |   INPUT:
# |     << pipeline.parameters.GHA_Action >>
# 2. [#/workflows/when] subject must not be valid against schema {\"description\":\"cannot use both 'when' and 'unless'\",\"allOf\":[{\"required\":[\"when\"]},{\"required\":[\"unless\"]}]}
# |   SCHEMA:
# |     not:
# |       description: cannot use both 'when' and 'unless'
# |       allOf:
# |       - required:
# |         - when
# |       - required:
# |         - unless
# |   INPUT:
# |     << pipeline.parameters.GHA_Action >>
```

### Minimum reproduction code

https://gist.github.com/realnc/796e8302d6e546c95fd4e274b9686091

### Expected behavior

```when: << pipeline.parameters.GHA_Action >>``` should prevent the workflow from running rather than resulting in the pipeline to fail.

### GitHub Action Version

1.0.4
