### ISSUE TITLE
Request: `pull_request_target` support

### ISSUE THREAD

**Issue by carmocca** [CircleCI-Public/trigger-circleci-pipeline-action#27]
### Is there an existing issue that is already proposing this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe it

This GitHub action requires access to a `CCI_TOKEN`. Because of GitHub's security, forks do not have access to secrets. So the CircleCI job will not trigger:

```
Failed to trigger CircleCI Pipeline
  Error: Error: Request failed with status code 403
  Error: Request failed with status code 403
```

To resolve this, I thought of using the `pull_request_target` event, where CI runs with the base of the branch so secrets can be securely shared. Then checking out the HEAD of the PR to trick CircleCI into using this ref:

```yaml
on:
  pull_request_target:

jobs:
  # https://github.com/marketplace/actions/trigger-circleci-pipeline
  trigger-circleci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha }}
      - uses: CircleCI-Public/trigger-circleci-pipeline-action@v1.0.5
        env:
          CCI_TOKEN: ${{ secrets.CCI_TOKEN }}
```

However, the triggering branch still points to `master`:

![image](https://user-images.githubusercontent.com/11067892/189698810-38afebf6-1c1c-417d-bc83-d7083a196d0b.png)

### Describe the solution you'd like

Any suggestion on how to resolve this? I guess this logic would need to be adapted: https://github.com/CircleCI-Public/trigger-circleci-pipeline-action/blob/d8e1aed1a2524b8982a8557aaad544155c560d90/index.js#L17-L28

### Teachability, documentation, adoption, migration strategy

An addition to the README would be sufficient.

### What is the motivation / use case for changing the behavior?

It should work for forks.
