### ISSUE TITLE
Request: Define Outputs

### ISSUE THREAD

**Issue by whatisdot** [CircleCI-Public/trigger-circleci-pipeline-action#28]
### Is there an existing issue that is already proposing this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe it

Triggering a pipeline works as expected, but there's no way to consume and use the response in following steps. To do that, we need the action to [define outputs](https://docs.github.com/en/actions/using-jobs/defining-outputs-for-jobs) for the job.

### Describe the solution you'd like

Descriptions taken from the [CircleCI API documentation](https://circleci.com/docs/api/v2/index.html#operation/triggerPipeline):
```yaml
outputs:
  id:
    description: The unique ID of the pipeline.
  state:
    description: The current state of the pipeline.
  number:
    description: The number of the pipeline.
  created_at:
    description: The date and time the pipeline was created.
```

### Teachability, documentation, adoption, migration strategy

_Descriptions taken from the [CircleCI API documentation](https://circleci.com/docs/api/v2/index.html#operation/triggerPipeline)._

# Outputs
Field | Data Type | Description
-- | -- | --
id | string (uuid) | The unique ID of the pipeline.
state | string (Enum: "created" "errored" "setup-pending" "setup" "pending") | The current state of the pipeline.
number | integer (int64) | The number of the pipeline.
created_at | string (date-time) | The date and time the pipeline was created.

### What is the motivation / use case for changing the behavior?

Adds a backwards-compatible feature that enables teams to use the pipeline ID and date created in downstream workflow actions.
