### ISSUE TITLE
Request: Allow to specify API version for triggering URL `url`

### ISSUE THREAD

**Issue by yirueilu-b** [CircleCI-Public/trigger-circleci-pipeline-action#49]
### Is there an existing issue that is already proposing this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe it

I am trying to use `trigger-circleci-pipeline-action` to trigger my pipeline with my private API endpoint.

Though I could set `CCI_HOST` succesfully, still got 404.

Later I found my private API endpoint is like `https://circleci.xxx.com/api/v1.1/project/gh/[ORG]/[REPO]/pipeline`

And found [this line](https://github.com/CircleCI-Public/trigger-circleci-pipeline-action/blob/main/index.js#L68) fixed the version as `v2` for the triggering URL. It seems that there is no way to set my private endpoint as triggering url for now.
```javascript
const url = `https://${host}/api/v2/project/gh/${repoOrg}/${repoName}/pipeline`;
```

### Describe the solution you'd like

 Is it possible to add a new env variable like `CCI_VER`?

Or maybe a env variable `CCI_URL` to allow user to set the complete endpoint?

### Teachability, documentation, adoption, migration strategy

```yaml
    steps:
      - name: Trigger Cicle CI Building Pipeline
        id: trigger_building_pipe
        uses: CircleCI-Public/trigger-circleci-pipeline-action@vX.X.X
        env:
          CCI_TOKEN: $
          # or CCI_VER: v1.1
          CCI_URL: https://circleci.xxx.com/api/v1.1/project/gh/[ORG]/[REPO]/pipeline
```

### What is the motivation / use case for changing the behavior?

Support private endpoint more generally
