### ISSUE TITLE
Request: Ability to approve circleci jobs

### ISSUE THREAD

**Issue by benatshippabo** [CircleCI-Public/trigger-circleci-pipeline-action#58]
### Is there an existing issue that is already proposing this?

- [X] I have searched the existing issues

### Describe the solution you'd like

Can we also have the ability to auto approve workflows based on github events as well? For example, we have the following workflow:

```yml
workflows:
  version: 2
  build:
    jobs:
      - server_unit_tests
      - server_integration_test
      - frontend_tests
      - e2e_tests_trigger:
          type: approval
      - e2e_tests:
          requires:
            - e2e_tests_trigger
```

Instead of triggering the pipeline, can we also have this action auto approve based on github actions? My goal is to have the job auto approve based on a label `merge`

### Teachability, documentation, adoption, migration strategy

```yml
on:
  pull_request:
    types: [labeled]
jobs:
  trigger-circleci:
    if: ${{ github.event.label.name == 'merge' }}
    runs-on: ubuntu-latest
    steps:
      - name: <customize name>
        id: <customize id>
        uses: CircleCI-Public/trigger-circleci-pipeline-action@v1.0.5
        with:
          - APPROVAL_TRIGGER=e2e_tests_trigger
        env:
          CCI_TOKEN: ${{ secrets.CCI_TOKEN }}
```

### What is the motivation / use case for changing the behavior?

Need a way for merge queues to be able to auto trigger circleci approval jobs
