### ISSUE TITLE
Bug: Triggering via issue_comment Action Kicks Off Workflow For Incorrect Commit/Branch

### ISSUE THREAD

**Issue by jblacker** [CircleCI-Public/trigger-circleci-pipeline-action#61]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

When I attempt to trigger a workflow in CircleCI from this GitHub Action on the created `issue_comment` event it works properly, but then starts the workflow on the incorrect branch within CircleCI. It appears to start the pipeline for the commit at HEAD of `main` rather than on the branch/commit in the Pull Request that triggered the action.

### Minimum reproduction code

https://gist.github.com/jblacker/4f8b3d87b3b0b60a00c166e05d6ced81

### Steps to reproduce

1. Use this example in my gist to trigger a pipeline on CircleCI
2. Create a new branch that's not the default and open a PR
3. Write the comment on the PR "/deploy-staging"
4. Check CircleCI you'll see that it triggered `main` (or whatever your default is) rather than the head of the current branch of the PR.

### Expected behavior

I would have expected the branch that the PR is for to be triggered in CircleCI.

### GitHub Action Version

1.0.5

### Other

Here's the trigger on the CircleCI side of things:
```
when:
      or:
        - and:
          - equal: [<<pipeline.parameters.deploy_branch>>, <<pipeline.git.branch>>]
          - equal: [<<pipeline.parameters.deploy>>, true]
        - and:
          - <<pipeline.parameters.GHA_Action>>
          - equal: [<<pipeline.parameters.GHA_Event>>, "issue_comment"]
          - equal: [<<pipeline.parameters.GHA_Meta>>, "DEPLOY_STAGING"]
```
