### ISSUE TITLE
Bug: Triggering pipeline returns 404; but green on CCI

### ISSUE THREAD

**Issue by RicardoMonteiroSimoes** [CircleCI-Public/trigger-circleci-pipeline-action#62]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

Right now I am changing our CCI setup to trigger through a GH Action. This is to allow us to disable these system tests via a specific label. Now, this appears to be working for anything that runs directly on GH.

Using the action from this repo (Also upgraded manually to 1.1, please refactor the example!), I have changed our `config.yml` file to check if `GH_Action` matches. This appears to work; as now the tests don't run, and my new job that checks if it _doesn't_ match runs succesfully: 
<img width="640" alt="image" src="https://github.com/CircleCI-Public/trigger-circleci-pipeline-action/assets/30594398/b8af79aa-3b59-4448-aecc-6eb92279500a">

Now my problem is that, the only reason these fail, is because the action itself returns a 404...
<img width="745" alt="image" src="https://github.com/CircleCI-Public/trigger-circleci-pipeline-action/assets/30594398/97c1784f-c979-429a-968b-6d9e44869c32">

The action setup is as simple as it gets:

```yml
name: Run CircleCi tests
on:
  pull_request:
    types: [opened, synchronize, reopened]
jobs:
  trigger-circleci:
    runs-on: ubuntu-latest
    steps:
      - name: run system tests
        id: cci_system_tests
        uses: CircleCI-Public/trigger-circleci-pipeline-action@v1.1.0
        env:
          CCI_TOKEN: ${{ secrets.CIRCLE_CI_TOKEN }}
```

So I am not entirely sure how this is supposed to work. 

### Minimum reproduction code

Please see above

### Expected behavior

It should correctly trigger the test with the right parameters, so that it can run the tests, and report back in the PR action if they are passing or not.

### GitHub Action Version

1.1.0
