### ISSUE TITLE
Bug: Major reference is not resolvable

### ISSUE THREAD

**Issue by LecrisUT** [CircleCI-Public/trigger-circleci-pipeline-action#63]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

It is common for Github actions to be able to reference by the major/major.minor versions, e.g.:
```
  trigger-circleci:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger CircleCI
        uses: CircleCI-Public/trigger-circleci-pipeline-action@v1
```

However tags or branches for `v1` and `v1.1` are missing

### Minimum reproduction code

Above

### Expected behavior

Above
